//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestingSystemEntities : DbContext
    {
        public TestingSystemEntities()
            : base("name=TestingSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CollectionType> CollectionTypes { get; set; }
        public virtual DbSet<CPU_Config> CPU_Config { get; set; }
        public virtual DbSet<DataType> DataTypes { get; set; }
        public virtual DbSet<PC_Config> PC_Config { get; set; }
        public virtual DbSet<RAM_Config> RAM_Config { get; set; }
        public virtual DbSet<RAM_Modules> RAM_Modules { get; set; }
        public virtual DbSet<RAM_Modules_Config> RAM_Modules_Config { get; set; }
        public virtual DbSet<Sort_Config> Sort_Config { get; set; }
        public virtual DbSet<SortResult> SortResults { get; set; }
        public virtual DbSet<SortsAlgorithm> SortsAlgorithms { get; set; }
    }
}
