//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_Config
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PC_Config()
        {
            this.SortResults = new HashSet<SortResult>();
        }
    
        public int ID { get; set; }
        public int RAM_ID { get; set; }
        public int CPU_ID { get; set; }
    
        public virtual CPU_Config CPU_Config { get; set; }
        public virtual RAM_Config RAM_Config { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SortResult> SortResults { get; set; }
    }
}
