//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAM_Modules_Config
    {
        public int ID { get; set; }
        public int ID_Modules { get; set; }
        public int ID_Config { get; set; }
    
        public virtual RAM_Config RAM_Config { get; set; }
        public virtual RAM_Modules RAM_Modules { get; set; }
    }
}
