//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SortResult
    {
        public int ID { get; set; }
        public int ID_Sort_Config { get; set; }
        public int ID_PC_Config { get; set; }
        public int Time { get; set; }
    
        public virtual PC_Config PC_Config { get; set; }
        public virtual Sort_Config Sort_Config { get; set; }
    }
}
