//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sort_Config
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sort_Config()
        {
            this.SortResults = new HashSet<SortResult>();
        }
    
        public int ID { get; set; }
        public int ID_CollectionType { get; set; }
        public int ID_DataType { get; set; }
        public int ID_SortsAlgorithms { get; set; }
    
        public virtual CollectionType CollectionType { get; set; }
        public virtual DataType DataType { get; set; }
        public virtual SortsAlgorithm SortsAlgorithm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SortResult> SortResults { get; set; }
    }
}
